### PR TITLE
fix issue#8 package scope for ReadRoot<Type> call in translateCapn.go

### PR DESCRIPTION
**Pull request by fvbock**
see https://github.com/glycerine/bambam/issues/8

### CODE REVIEW

**Comment by fvbock** [comment]
there were some tests failing: one with a timeout and others seemed to have mismatches in the generated code having a tab or 4 spaces prefixed on lines where it was not expected. *should* be i ok i guess?

**Comment by glycerine** [comment]
This PR has some problems. In general you should expect to make all tests in the test suite pass before a pull can be considered.

Lots of tests failing for two reasons: there are references to testpkg[.] still in the test files. These are easily fixed with `perl -pi -e 's/testpkg[.]//g' *test.go`.

However there is a more serious problem that the Test003WriteReadThroughGeneratedTranslationCode test fails: this is the main round trip test that checks that everything works. Somehow, after application of this PR, there are missing functions, e.g. NewNester1CapnList. See below for the complete list.

~~~
 cd testdir_012267003
Jasons-MacBook-Pro:testdir_012267003 jasona$ ls
go.capnp        rw.go.txt       schema.capnp.go
rw.go           schema.capnp        translateCapn.go
Jasons-MacBook-Pro:testdir_012267003 jasona$ go build
# github.com/fvbock/bambam/testdir_012267003
./translateCapn.go:106: undefined: NewNester1CapnList
./translateCapn.go:216: undefined: NewPtr1CapnList
./translateCapn.go:355: undefined: NewNester2CapnList
./translateCapn.go:367: undefined: NewPtr2CapnList
./translateCapn.go:471: undefined: NewNester1CapnList
./translateCapn.go:491: undefined: NewNester2CapnList
Jasons-MacBook-Pro:testdir_012267003 jasona$ ls
~~~

**Comment by fvbock** [comment]
oh ok. for some reason i had tests not pass before too and i thought it was not related. sorry about that. will fix the other stuff.

**Comment by fvbock** [comment]
hm. i can't reproduce the fail on `Test003WriteReadThroughGeneratedTranslationCode`. the only thing i could see was an occasional timeout/panic when running goconvey, but it would still build normally in the testdir:

```
github.com/fvbock/bambam/testdir_291864932 [testdir_291864932 (master)] $ go build
github.com/fvbock/bambam/testdir_291864932 [testdir_291864932 (master)] $ ./testdir_291864932 
Load() data matched Saved() data.
```

after fixing the tests failing on the missing prefix everything passes for me.

**Comment by glycerine** [comment]
I can't repro that problem on a different computer either. Looks good. Merged. Thanks Florian.

**Comment by fvbock** [comment]
np. and thanks for bambam and your work on go-capnproto!

**Pull request merged**
